version: '2'
services:
  nginx:
    build: ./docker/nginx
    container_name: sprintsync-nginx
    ports:
      - "8001:80"
    depends_on:
      - php-fpm
    volumes:
      - ./app:/usr/src/app

  php-fpm:
    build: ./docker/php-fpm
    container_name: sprintsync-phpfpm
    volumes:
      - ./app:/usr/src/app
networks:
  sprintsync:
    driver: bridge